
sylius_resource:
  resources:
    ikuzo_avis_verifies.channel_review:
      driver: doctrine/orm
      classes:
        model: Ikuzo\SyliusAvisVerifiesPlugin\Entity\ChannelReview
        interface: Ikuzo\SyliusAvisVerifiesPlugin\Entity\ChannelReviewInterface
        repository: Ikuzo\SyliusAvisVerifiesPlugin\Repository\ChannelReviewRepository

sylius_ui:
  events:
    sylius.admin.order.show.sidebar:
      blocks:
        avis_verifies:
          template: '@IkuzoSyliusAvisVerifiesPlugin/Order/Show/_avisverifies.html.twig'
          priority: 5
    sylius.admin.channel.form.second_column_content:
      blocks:
        avis_verifies:
          template: '@IkuzoSyliusAvisVerifiesPlugin/Channel/_form.html.twig'
          priority: 5

sylius_grid:
  grids:
    sylius_admin_product_review:
      fields:
        source:
          type: twig
          label: ikuzo_avis_verifies.grid.filters.source
          options:
            template: '@IkuzoSyliusAvisVerifiesPlugin/Grid/Column/_source.html.twig'
      filters:
        author:
          type: string
          label: sylius.ui.customer
        source:
          type: select
          label: ikuzo_avis_verifies.grid.filters.source
          form_options:
            choices: 
              Sylius: null
              Avis vérifiés: avisverifies

    sylius_admin_order:
      filters:
        avisVerifiesEmailsSent:
          type: boolean
          label: ikuzo_avis_verifies.grid.filters.email_sent
    ikuzo_avis_verifies_channel_review:
      driver:
        options:
          class: "%ikuzo_avis_verifies.model.channel_review.class%"
      sorting:
        id: desc
      fields:
        id:
          type: string
        channel:
          type: twig
          label: sylius.ui.channel
          sortable: channel.code
          options:
            template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
          path: channel
        number:
          type: twig
          label: sylius.ui.number
          sortable: ~
          options:
            template: "@SyliusAdmin/Order/Grid/Field/number.html.twig"
          path: order
        firstname:
          type: string
          label: ikuzo_avis_verifies.ui.firstname
        lastname:
          type: string
          label: ikuzo_avis_verifies.ui.lastname
        content:
          type: string
          label: ikuzo_avis_verifies.ui.content
        rate:
          type: string
          label: ikuzo_avis_verifies.ui.rate
        reviewedAt:
          type: datetime
          label: ikuzo_avis_verifies.ui.reviewed_at
      filters:
        channel:
          type: entity
          label: sylius.ui.channel
          form_options:
            class: "%sylius.model.channel.class%"
        order_number:
          type: string
          label: sylius.ui.order
          options:
            fields: [order.number, order.customer.email, order.customer.firstName, order.customer.lastName]
        reviewedAt:
          type: date
          label: sylius.ui.date
          options:
            field: reviewedAt
            inclusive_to: true

winzou_state_machine:
  sylius_order:
    callbacks:
      after:
        sylius_send_avisverifies:
          on: ["fulfill"]
          do: ["@ikuzo_sylius_avis_verifies.event_listener.on_order_fulfilled", "sendToAvisVerifies"]
          args: ["object"]